#!/usr/bin/env node
/**
 * write-env.js
 *
 * Reads cdk-outputs.json (generated by `cdk deploy --outputs-file cdk-outputs.json`)
 * and writes the corresponding NEXT_PUBLIC_* variables into the portfolio's .env.local.
 *
 * Usage (from infrastructure/):
 *   npm run env
 *
 * Or from anywhere:
 *   node infrastructure/scripts/write-env.js
 */

const fs = require("fs");
const path = require("path");

const outputsFile = path.join(__dirname, "..", "cdk-outputs.json");
const envFile = path.join(__dirname, "..", "..", ".env.local");

if (!fs.existsSync(outputsFile)) {
  console.error(
    "❌  cdk-outputs.json not found.\n" +
    "    Run `cdk deploy --outputs-file cdk-outputs.json` first."
  );
  process.exit(1);
}

const outputs = JSON.parse(fs.readFileSync(outputsFile, "utf-8"));
const stack = outputs["AgendaStack"];

if (!stack) {
  console.error("❌  AgendaStack not found in cdk-outputs.json.");
  process.exit(1);
}

const userPoolId    = stack["UserPoolId"];
const clientId      = stack["UserPoolClientId"];
const identityPoolId = stack["IdentityPoolId"];
const region        = stack["Region"] ?? "eu-west-1";

if (!userPoolId || !clientId || !identityPoolId) {
  console.error("❌  Missing required outputs in cdk-outputs.json. Re-deploy the stack.");
  process.exit(1);
}

let existingApiKey = "";
let existingCalendarId = "primary";

if (fs.existsSync(envFile)) {
  const currentEnv = fs.readFileSync(envFile, "utf-8");
  const apiKeyMatch = currentEnv.match(/^NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY=(.*)$/m);
  const calendarIdMatch = currentEnv.match(/^NEXT_PUBLIC_GOOGLE_CALENDAR_ID=(.*)$/m);
  if (apiKeyMatch) existingApiKey = apiKeyMatch[1];
  if (calendarIdMatch) existingCalendarId = calendarIdMatch[1];
}

const envContent = `# ============================================================
# Auto-generated by infrastructure/scripts/write-env.js
# Source: cdk-outputs.json — DO NOT EDIT MANUALLY
# Regenerate with: cd infrastructure && npm run env
# ============================================================

# AWS Cognito — User Pool (Authentication)
NEXT_PUBLIC_COGNITO_USER_POOL_ID=${userPoolId}
NEXT_PUBLIC_COGNITO_CLIENT_ID=${clientId}

# AWS Cognito — Identity Pool (Temporary DynamoDB credentials)
NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID=${identityPoolId}

# AWS Region
NEXT_PUBLIC_AWS_REGION=${region}

# ============================================================
# Google Calendar API (FASE 2 — pending configuration)
# ============================================================
# NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY=
# NEXT_PUBLIC_GOOGLE_CALENDAR_ID=primary
${existingApiKey ? `NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY=${existingApiKey}` : ""}
${existingCalendarId !== "primary" ? `NEXT_PUBLIC_GOOGLE_CALENDAR_ID=${existingCalendarId}` : ""}
`;

fs.writeFileSync(envFile, envContent, "utf-8");

console.log("✅  .env.local updated successfully!\n");
console.log(`   NEXT_PUBLIC_COGNITO_USER_POOL_ID   = ${userPoolId}`);
console.log(`   NEXT_PUBLIC_COGNITO_CLIENT_ID       = ${clientId}`);
console.log(`   NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID = ${identityPoolId}`);
console.log(`   NEXT_PUBLIC_AWS_REGION              = ${region}`);
console.log("\n👉  Restart `npm run dev` in the portfolio root to pick up the new values.");
